#!/usr/bin/env python3
"""optimize_num_ctx: pick an Ollama num_ctx that fits your GPU's VRAM.

Given one or more local Ollama models (or raw .gguf files), this tool:

1. Reads the model's GGUF metadata (weights are never loaded).
2. Infers its architecture kind (dense / hybrid attention+SSM / MLA / sliding-window).
3. Estimates the KV-cache cost per context token.
4. Computes a safe `num_ctx` that fits the detected VRAM (minus a configurable
   compute/overhead reserve and safety headroom), capped at the model's native
   context length.
5. Generates `Modelfile`s (and optionally creates the alternate tags via
   `ollama create`), so you get a new tag with the context baked in.

It is portable and dependency-free: Python 3.9+ standard library only, plus the
`ollama` CLI and (for GPU auto-detection) `nvidia-smi` from the NVIDIA driver.

Usage examples
--------------
# Show a table of recommended num_ctx for specific models
python optimize_num_ctx.py qwen3:8b llama3.1:70b --info-only

# Auto-discover every installed local model and show a table
python optimize_num_ctx.py --info-only

# Generate Modelfiles into ./modelfiles (one per model), no ollama create
python optimize_num_ctx.py qwen3:8b gpt-oss:20b

# Generate AND create the alternate tags
python optimize_num_ctx.py qwen3:8b gpt-oss:20b --apply

# Override detected VRAM (needed on AMD / Apple Silicon or if no nvidia-smi)
python optimize_num_ctx.py qwen3:8b --vram-mib 122880 --info-only
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

from ollama_gguf import (
    GGUFError,
    DEFAULT_OVERHEAD_GB,
    infer_layout,
    kv_bytes_per_token,
    parse_gguf,
    resolve_gguf,
)

# --------------------------------------------------------------------------- #
# GPU VRAM detection
# --------------------------------------------------------------------------- #
def detect_vram_mib(prefer_mib=None):
    """Return total GPU VRAM in MiB, or None if it cannot be determined."""
    if prefer_mib:
        return int(prefer_mib)
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=memory.total", "--format=csv,noheader,nounits"],
            text=True,
        )
        values = [int(line.strip()) for line in out.strip().splitlines() if line.strip().isdigit()]
        if values:
            return max(values)
    except (OSError, subprocess.SubprocessError, ValueError):
        pass
    env = os.environ.get("OLLAMA_CTX_VRAM_MIB")
    if env:
        try:
            return int(env)
        except ValueError:
            pass
    return None


# --------------------------------------------------------------------------- #
# Context recommendation
# --------------------------------------------------------------------------- #
NICE_CONTEXTS = [1024, 2048, 4096, 8192, 16384, 32768, 49152, 65536, 98304,
                 131072, 196608, 262144]


def _nice_ctx(value):
    """Largest 'nice' context value <= value (0 if none)."""
    chosen = 0
    for c in NICE_CONTEXTS:
        if c <= value:
            chosen = c
        else:
            break
    return chosen


def recommend(layout, weight_bytes, vram_mib, overhead_gb, headroom_gb, dtype,
              min_ctx):
    """Compute the recommended num_ctx for one model.

    Returns a dict with the computed values (max_ctx, recommended, kv_per_token,
    estimated VRAM, and the inputs used).
    """
    kv_tok = kv_bytes_per_token(layout, dtype)
    native = layout.get("native_ctx")
    gb = 1024 ** 3
    vram = vram_mib * 1024 * 1024

    reserved = (overhead_gb + headroom_gb) * gb
    available_for_kv = vram - weight_bytes - reserved

    if kv_tok > 0:
        max_ctx = int(available_for_kv / kv_tok)
    else:
        max_ctx = 0
    if native:
        max_ctx = min(max_ctx, native)
    recommended = _nice_ctx(max_ctx)
    if min_ctx and recommended < min_ctx:
        recommended = min_ctx
    if max_ctx and recommended > max_ctx:
        # The --min-ctx floor never overrides the hard VRAM ceiling.
        recommended = max_ctx

    est_vram_gb = (weight_bytes + (kv_tok * recommended if kv_tok else 0) + reserved) / gb
    return {
        "kv_bytes_per_token": kv_tok,
        "native_ctx": native,
        "max_ctx": max_ctx,
        "recommended": recommended,
        "weight_gb": weight_bytes / gb,
        "est_vram_gb": est_vram_gb,
        "reserved_gb": overhead_gb + headroom_gb,
    }


# --------------------------------------------------------------------------- #
# Modelfile generation
# --------------------------------------------------------------------------- #
def generate_modelfile(model_tag, num_ctx, base=None):
    """Return the text of a Modelfile for ``model_tag`` with a baked-in num_ctx."""
    base = base or model_tag
    lines = [
        f"FROM {base}",
        "# Alternate tag optimised for GPU VRAM (generated by optimize_num_ctx.py)",
        f"PARAMETER num_ctx {num_ctx}",
        "",
    ]
    return "\n".join(lines)


def run_ollama_create(tag, modelfile_path):
    """Create an Ollama tag from a Modelfile (uses the installed `ollama` CLI)."""
    cmd = ["ollama", "create", tag, "-f", modelfile_path]
    print(f"  $ ollama create {tag}")
    subprocess.run(cmd, check=True)


# --------------------------------------------------------------------------- #
# Ollama tag discovery
# --------------------------------------------------------------------------- #
def list_local_tags():
    """Return installed local (non-cloud) Ollama tags via `ollama list`."""
    try:
        out = subprocess.check_output(["ollama", "list"], text=True)
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"  ! could not run `ollama list`: {exc}", file=sys.stderr)
        return []
    tags = []
    for line in out.splitlines()[1:]:  # skip header
        if not line.strip():
            continue
        parts = line.split()
        if not parts:
            continue
        tag = parts[0]
        # skip cloud / virtual models (no size / size == '-')
        size = parts[2] if len(parts) > 2 else "-"
        if size == "-":
            continue
        tags.append(tag)
    return tags


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def build_parser():
    p = argparse.ArgumentParser(
        description="Choose an Ollama num_ctx that fits your GPU VRAM and generate Modelfiles.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("models", nargs="*",
                   help="Ollama tags or .gguf file paths (default: all installed local models)")
    p.add_argument("--vram-mib", type=int, default=None,
                   help="Override total VRAM in MiB (optional; auto-detected via nvidia-smi)")
    p.add_argument("--overhead-gb", type=float, default=DEFAULT_OVERHEAD_GB,
                   help="Compute/activation reserve in GB (default 4)")
    p.add_argument("--headroom-gb", type=float, default=4,
                   help="Safety headroom in GB below the GPU limit (default 4)")
    p.add_argument("--dtype", choices=["f16", "f32"], default="f16",
                   help="KV cache dtype (default f16)")
    p.add_argument("--min-ctx", type=int, default=8192,
                   help="Never recommend below this (default 8192)")
    p.add_argument("--outdir", default="modelfiles",
                   help="Directory to write Modelfiles into (default ./modelfiles)")
    p.add_argument("--info-only", action="store_true",
                   help="Print the recommendation table only; do not write Modelfiles")
    p.add_argument("--apply", action="store_true",
                   help="Also run `ollama create` for every generated Modelfile")
    p.add_argument("--overwrite", action="store_true",
                   help="Overwrite existing Modelfile outputs (default: skip)")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)

    vram_mib = detect_vram_mib(args.vram_mib)
    if not vram_mib:
        print("! Could not detect VRAM. Use --vram-mib or set OLLAMA_CTX_VRAM_MIB.",
              file=sys.stderr)
        return 2
    print(f"GPU VRAM: {vram_mib} MiB (~{vram_mib / 1024:.1f} GiB)")
    print(f"Reserve:  {args.overhead_gb + args.headroom_gb} GB "
          f"(overhead {args.overhead_gb} + headroom {args.headroom_gb}) | "
          f"KV dtype {args.dtype}\n")

    models = args.models or list_local_tags()
    if not models:
        print("! No models given and none discovered. Pass tags explicitly.", file=sys.stderr)
        return 2

    rows = []
    for target in models:
        try:
            gguf, weight = resolve_gguf(target)
        except GGUFError as exc:
            print(f"! {target}: {exc}", file=sys.stderr)
            continue
        try:
            _version, _tcount, meta = parse_gguf(gguf)
        except GGUFError as exc:
            print(f"! {target}: {exc}", file=sys.stderr)
            continue
        try:
            layout = infer_layout(meta)
            rec = recommend(layout, weight, vram_mib, args.overhead_gb, args.headroom_gb,
                            args.dtype, args.min_ctx)
        except GGUFError as exc:
            print(f"! {target}: {exc}", file=sys.stderr)
            continue
        except TypeError as exc:
            print(f"! {target}: could not infer KV geometry ({exc}); skipped", file=sys.stderr)
            continue
        rows.append((target, layout, rec, gguf))

    if not rows:
        print("! No models could be analysed.", file=sys.stderr)
        return 1

    # ---- table ----
    hdr = f"{'MODEL':44s} {'wt GB':>7s} {'KV/tok':>8s} {'kind':<14s} {'native':>9s} {'max':>9s} {'rec ctx':>8s} {'~VRAM':>8s}"
    print(hdr)
    print("-" * len(hdr))
    for target, layout, rec, _gguf in rows:
        print(f"{target[:44]:44s} {rec['weight_gb']:7.1f} {rec['kv_bytes_per_token']:8d} "
              f"{layout['kind'][:14]:<14s} {str(rec['native_ctx'] or '-'):>9s} "
              f"{rec['max_ctx']:9d} {rec['recommended']:8d} {rec['est_vram_gb']:8.1f}")

    print()
    for target, layout, rec, gguf in rows:
        print(f"  {target}: {layout['detection']}")

    if args.info_only:
        return 0

    # ---- write Modelfiles ----
    os.makedirs(args.outdir, exist_ok=True)
    written = []
    for target, layout, rec, _gguf in rows:
        tag = target if ":" in target else f"{target}:latest"
        safe = target.replace("/", "-").replace(":", "-")
        out = os.path.join(args.outdir, f"{safe}-ctx{rec['recommended']}")
        if os.path.exists(out) and not args.overwrite:
            print(f"  ! skip {out} (exists; use --overwrite)")
            continue
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(generate_modelfile(target, rec["recommended"]))
        written.append((tag, out, rec["recommended"]))
        print(f"  + wrote {out}  (num_ctx {rec['recommended']})")

    # ---- optionally apply ----
    if args.apply:
        print()
        for tag, out, _nc in written:
            run_ollama_create(tag, out)

    print("\nDone.")
    if written:
        print(f"Modelfiles written to {os.path.abspath(args.outdir)}. "
              f"Use `ollama create <tag> -f <file>` or re-run with --apply.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
